version: "3"
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root12345
      MONGO_INITDB_DATABASE: graphql
    ports:
      - "27017:27017"
    networks:
      - node-webapp-network
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - node-webapp-network
networks:
  node-webapp-network:
    driver: bridge